name: autoreset_rl
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - astroid=2.0.4
  - blas=1.0
  - bleach=1.5.0
  - ca-certificates=2021.1.19
  - certifi=2020.6.20
  - cudatoolkit=8.0
  - cudnn=7.1.3
  - dbus=1.13.18
  - expat=2.2.10
  - fontconfig=2.13.0
  - freetype=2.10.4
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - html5lib=0.9999999
  - icu=58.2
  - intel-openmp=2019.3
  - isort=4.3.4
  - jpeg=9b
  - kiwisolver=1.0.1
  - lazy-object-proxy=1.3.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.6.0
  - libstdcxx-ng=8.2.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.9
  - markdown=2.6.11
  - mccabe=0.6.1
  - mkl=2018.0.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - ncurses=6.1
  - numpy=1.15.2
  - numpy-base=1.15.2
  - openssl=1.0.2u
  - patsy=0.5.0
  - pcre=8.44
  - pip=10.0.1
  - protobuf=3.6.0
  - pylint=2.1.1
  - pyqt=5.9.2
  - python=3.5.6
  - qt=5.9.6
  - readline=7.0
  - seaborn=0.9.0
  - setuptools=40.2.0
  - sip=4.19.8
  - six=1.11.0
  - sqlite=3.27.2
  - statsmodels=0.9.0
  - tbb=2020.3
  - tbb4py=2018.0.5
  - tensorflow-gpu=1.4.1
  - tensorflow-gpu-base=1.4.1
  - tk=8.6.8
  - tornado=5.1.1
  - typed-ast=1.1.0
  - werkzeug=0.14.1
  - wheel=0.31.1
  - wrapt=1.10.11
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - absl-py==0.7.1
    - annoy==1.8.3
    - backcall==0.1.0
    - chardet==3.0.4
    - cycler==0.10.0
    - cython==0.29.7
    - decorator==4.4.0
    - enum34==1.1.6
    - future==0.17.1
    - futures==3.1.1
    - gin-config==0.4.0
    - glfw==2.1.0
    - gym==0.9.3
    - idna==2.8
    - inputimeout==1.0.4
    - ipython==7.6.1
    - ipython-genutils==0.2.0
    - jedi==0.14.0
    - joblib==0.14.1
    - lxml==4.3.3
    - matplotlib==2.0.2
    - mujoco-py==0.5.7
    - natsort==6.0.0
    - networkx==2.2
    - olefile==0.46
    - pandas==0.20.2
    - parso==0.5.0
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pillow==4.3.0
    - prompt-toolkit==2.0.9
    - ptyprocess==0.6.0
    - py3nvml==0.2.3
    - pygame==1.9.3
    - pyglet==1.3.2
    - pygments==2.4.2
    - pyopengl==3.1.0
    - pyparsing==2.3.1
    - python-dateutil==2.8.0
    - pytz==2019.1
    - pywavelets==1.0.2
    - pyyaml==5.1
    - requests==2.21.0
    - scikit-image==0.13.0
    - scikit-learn==0.22.2.post1
    - scipy==0.19.0
    - tensorflow-tensorboard==0.4.0
    - tqdm==4.32.2
    - traitlets==4.3.2
    - urllib3==1.24.1
    - wcwidth==0.1.7
    - xmltodict==0.12.0
    - xvfbwrapper==0.2.9